content/chainguard/chainguard-images/overview.md
This PR fixes a broken link in the Chainguard Images overview page.
=> Fixed link to Wolfi docs

content/software-security/videos/PyPI.md
The [WTF PyPI](https://edu.chainguard.dev/software-security/videos/pypi/) post has the wrong video embedded.
Documentation - change embedded YouTube video
Embed the correct WTF PyPI video from the Chainguard YouTube Account
Because we have the wrong video on the site.
Confirm that this [YouTube](https://www.youtube.com/watch?v=IvxWXk5jSsc) video appears on https://edu.chainguard.dev/software-security/videos/pypi/
Can test locally, pulling down the branch and running `npm install && npm run start`
=> fix: embed correct wtf PyPI video

content/open-source/apko/getting-started-with-apko.md
This PR fixes a link to the apko GitHub Action on the getting started guide (fix for #141).
=> #141 - Updated link to GH action on apko guide

content/open-source/apko/getting-started-with-apko.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
This PR will add a `-w/--working-directory` parameter to the `docker run` command to prevent adding the `/work` directory path as a prefix to the files.
To simplify the `docker run` command a little bit more 😇
/cc @erikaheidi @ltagliaferri
=> feat: specify working directory as /work

content/chainguard/chainguard-enforce/chainctl-docs/how-to-install-chainctl.md, content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-user-onboarding.md, content/ui/enforce-onboarding-quickstart.md
Purely cosmetic. 💄 
Updates the `chainctl` download URL to a prettier one at https://dl.enforce.dev
It makes a slightly more polished experience.
If we decide to change the storage backend in the future we can do it without changing this user-visible URL.
The installation instructions continue to work.
```
curl -o chainctl "https://dl.enforce.dev/chainctl_$(uname -s)_$(uname -m)"
```
=> update download links to use dl.enforce.dev

layouts/article/single.html
It looks like there is a sitemap issue because we still had breadcrumbs appearing on the HTML page despite removing it from the config file. I removed it now to support analytics. 
Signed-off-by: Lisa Tagliaferri
=> Remove breadcrumbs on page

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-policy-examples.md, content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-user-onboarding.md, content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/connecting-to-private-registries.md
Fix to sample policies to prevent warning being shown
This removes a warning shown when applying a policy. Without a set identify the following is returned via `chainctl policies apply...`
**- WARNING: missing field(s): spec.authorities[0].keyless.identities**
This warning is coming from an upstream update in Sigstore and could confuse someone going through Enforce within the academy
I've completed the academy walkthrough with the branch locally, I can complete the workshop material, and no warning is shown during the process.
=> fix: remove warning when applying policy

content/open-source/melange/getting-started-with-melange.md
Bug/Documentation
This PR adds the interactive terminal back to the Getting Started with Melange tutorial.
With the 0.2.2 release of [minicli/curly](https://github.com/minicli/curly/releases/tag/0.2.2) the `hello-minicli:test` image at the end of the tutorial now runs as expected. 
Test the tutorial and look for output like the following:
```
docker run --rm hello-minicli:test
Work is never as important as you think it is.
```
=> Add terminal back to melange getting started guide

content/open-source/sigstore/cosign/how-to-sign-a-container-with-cosign.md
I was going through the [How to Sign a Container with Cosign tutorial](https://edu.chainguard.dev/open-source/sigstore/cosign/how-to-sign-a-container-with-cosign/). Along the tutorial it was mentioned that the image tag used is `docker-username/hello-container` but the output expected was written `library` instead. 
Issue is not created since it is a minor change.
The tutorial mentioned that the image tag is `docker-username/hello-container` and the output got changed to `naming to docker.io/library/hello-container` which is `library` instead. 
Consistent naming of the image tag across the tutorial post. 
Checking directly on Netlify deploy preview.
=> Fix typo on tutorial that should be consistent using docker-username

layouts/partials/head/script-header.html
This PR adds `https://terminal.inky.wtf` to the `frame-src` portion of the Content Security Policy.
=> Update frame-src CSP to allow terminal.inky.wtf

layouts/partials/head/script-header.html
The [OpenAPI page](https://edu.chainguard.dev/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/api/) doesn't load because it calls JS/CSS from unpkg.com. This PR adds them, along with what I think is the SHA hash of the generated inline javascript for the page.
=> Add unpkg.com to style-src and script-src CSPs

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-events/index.md
Documentation
This PR adds Enforce events documentation.
Enforce emits cloudevents, but the various events and how to consume them are undocumented on Academy.
The events page should be visible under `/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-events/` on the preview site.
=> Add Enforce Events page

nginx.conf
This PR adds a `try_files...` directive to `nginx.conf`.
Without it, nginx redirects pages without a trailing slash to invalid URLs.
=> Add try_files directive to nginx.conf to fix invalid redirects

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/alternative-installation-methods.md
/kind feature
Document a recently added feature
:gift: This documents the recently added `cluster-{name,description}` fields, which optionally attach friendly descriptor metadata to clusters at registration.
Clusters show up with the desired name.
The steps can be run using the latest `chainctl`
=> Feature: document the `cluster-{name,description}` fields.

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/changelog.md
Documentation
This PR adds a changelog page that highlights customer facing changes to Enforce and `chainctl`.
It should be visible on the netlify preview site under `/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/changelog/`
=> Add Enforce/chainctl changelog page

content/open-source/melange/melange-pipelines/_index.md, content/open-source/melange/melange-pipelines/autoconf/configure.md, content/open-source/melange/melange-pipelines/autoconf/make-install.md, content/open-source/melange/melange-pipelines/autoconf/make.md, content/open-source/melange/melange-pipelines/cmake/build.md, content/open-source/melange/melange-pipelines/cmake/configure.md, content/open-source/melange/melange-pipelines/cmake/install.md, content/open-source/melange/melange-pipelines/fetch.md, content/open-source/melange/melange-pipelines/git-checkout.md, content/open-source/melange/melange-pipelines/meson/compile.md, content/open-source/melange/melange-pipelines/meson/configure.md, content/open-source/melange/melange-pipelines/meson/install.md, content/open-source/melange/melange-pipelines/patch.md, content/open-source/melange/melange-pipelines/split/dev.md, content/open-source/melange/melange-pipelines/split/infodir.md, content/open-source/melange/melange-pipelines/split/locales.md, content/open-source/melange/melange-pipelines/split/manpages.md, content/open-source/melange/melange-pipelines/split/static.md, content/open-source/melange/melange-pipelines/strip.md, content/open-source/melange/tutorials/_index.md, content/open-source/melange/tutorials/getting-started-with-melange.md
This PR brings a first version of the auto-generated melange pipeline docs to EDU and reorganizes melange docs structure to keep tutorials on a separate menu.
Ideally, these docs should not be manually edited, since our plan is to create a GitHub Action to periodically update them. The [deved-autodocs](https://github.com/chainguard-dev/deved-autodocs) repository has the source files to generate these docs, so for long term changes we should edit those sources.
Preview: https://deploy-preview-203--ornate-narwhal-088216.netlify.app/open-source/melange/melange-pipelines/git-checkout/
=> Auto-generated melange pipeline docs, reorganizing docs structure

content/chainguard/chainguard-enforce/chainctl-docs/_index.md, content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-user-onboarding.md, content/chainguard/chainguard-enforce/how-to-install-chainctl.md
Signed-off-by: ltagliaferri
Resolves #102 and also takes in the feedback on `chainctl`, adding the installation onto the landing page, and making the installation title more generic
=> Updates to onboarding and chainctl

nginx.conf
Bug fix 
The redirect in #212 has ended up returning URLs with the backend container's `listen       8080;` port in them e.g. 
```
curl -sI https://edu.chainguard.dev/chainguard/chainguard-enforce/chainctl-docs/how-to-install-chainctl/
HTTP/2 301
content-type: text/html
location: http://edu.chainguard.dev:8080/chainguard/chainguard-enforce/how-to-install-chainctl/
x-cloud-trace-context: bb1cc4a237af84f2c84d8c5259aedbcf;o=1
content-length: 169
date: Fri, 09 Dec 2022 19:42:56 GMT
server: Google Frontend
```
This PR ensures that redirects don't add a port, and instead preserve the request scheme and hostname.
Additionally, it gives a single place to add future rewrite rules as needed.
=> Fix port in redirected URLs, move rewrites to a map

content/chainguard/chainguard-enforce/how-to-install-chainctl.md
Documentation
This adds a one line command users can run to verify their `chainctl` binary with Cosign.
Run the command in the PR to verify a recent version of `chainctl`.
=> Add one-liner showing how to verify chainctl binary with cosign

.github/workflows/add-issues-to-project-images.yaml
Adding an issue syncer to our images project board.
Signed-off-by: Patrick Flynn <patrick@chainguard.dev>
=> add project images issue sync

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/network-requirements.md
Refs #444 
Update the Enforce network requirements page with information about Agent and SaaS registry access.
SaaS users may receive errors if the discovery agent cannot access their image registry or registries.
Check the [Network Requirements page](https://deploy-preview-467--ornate-narwhal-088216.netlify.app/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/network-requirements/#image-registry-access) on netlify.
=> Add note about registry access for Enforce SaaS to network reqs page
