content/chainguard/chainguard-enforce/chainctl-docs/how-to-install-chainctl.md, content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-user-onboarding.md
Add `curl` command back in that was deleted in error
=> Reinstate curl

content/chainguard/chainguard-images/faq.md
Signed-off-by: Adrian Mouat <adrian@chainguard.dev>
FAQ addition.
Describe relationship to distroless
Clarify our relationship with GCP distroless
@mattmoor @dlorenc might want to have a glance to make to sure what I've said is ok. I didn't mention that Matt and Dan started the Google project.
Proof read :)
=> Add GCP distroless to FAQ.

config/_default/config.toml, config/_default/menus/menus.en.toml, content/chainguard/chainguard-enforce/chainctl-docs/_index.md, content/chainguard/chainguard-enforce/chainguard-enforce-github/_index.md, content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/_index.md, content/open-source/melange/getting-started-with-melange.md, content/open-source/sigstore/cosign/an-introduction-to-cosign.md, content/open-source/sigstore/cosign/how-to-install-cosign.md, content/open-source/sigstore/cosign/how-to-sign-a-container-with-cosign.md, content/open-source/sigstore/cosign/how-to-sign-an-sbom-with-cosign.md, content/open-source/sigstore/cosign/how-to-sign-blobs-with-cosign.md, content/open-source/sigstore/rekor/an-introduction-to-rekor.md, content/open-source/sigstore/rekor/how-to-install-rekor.md, content/open-source/sigstore/rekor/how-to-query-rekor.md, content/open-source/sigstore/rekor/how-to-sign-and-upload-metadata-to-rekor.md, content/open-source/sigstore/rekor/install-a-rekor-instance.md
Resolves #137 and does some more minor reorganizing
=> Change order of docs

config/_default/config.toml
=> Base URL fix

content/open-source/wolfi/faq.md
This PR includes a question to clarify that wolfi apks should not be mixed with alpine apks.
=> Updating Wolfi FAQ

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-user-onboarding.md, content/ui/enforce-onboarding-quickstart.md
This adds a note about group creation following [this thread](https://chainguard-dev.slack.com/archives/C02SD39C6BW/p1664394544798869).
=> Add note about group creation

content/chainguard/chainguard-enforce/chainguard-enforce-github/install-enforce-github/index.md, content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/cloud-account-associations.md, content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/how-to-manage-iam-groups-in-chainguard-enforce.md, content/chainguard/chainguard-images/faq.md, content/chainguard/chainguard-images/images-compared.md, content/chainguard/chainguard-images/overview.md, content/contributors/erika-heidi/_index.md, content/contributors/john-speed-meyers/_index.md, content/open-source/melange/_index.md, content/open-source/melange/getting-started-with-melange.md, content/open-source/wolfi/faq.md, content/open-source/wolfi/overview.md, content/software-security/videos/distroless.md, content/software-security/videos/github-typosquatting.md
Updating descriptions, titles, more, based on audit.
=> Audit fixes

config/_default/config.toml, config/production/config.toml, netlify.toml
This PR sets additional parameters to the Netlify configuration file to fix the deploy preview. It was not necessary to change the configuration of the website.
We should check the Netlify preview to see if it was fixed, and make sure the production site keeps working as expected once changes are incorporated.
=> Fixing Netlify Deploy Preview

content/open-source/wolfi/faq.md
Bringing Wolfi FAQs to be in line with the ones on the Wolfi GitHub org page
Signed-off-by: Lisa Tagliaferri
=> Update Wolfi FAQs

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-kubernetes-faq.md
New Content
This PR adds a new article (an FAQ for Enforce for K8s). Related to issue #155  
Please double check the content, and pay attention to the TOC ordering. I think I figured it out but definitely adjust things if it seems necessary.
=> adding enforce for k8s FAQ

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-policies-ui/index.md
This PR fixes a few small typos I noticed in [How to create policies in the Chainguard Enforce Console](https://edu.chainguard.dev/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-policies-ui/). I made no changes to the existing content or screenshots other than fixing a couple typos.
Just a couple small copyedits.
I'm working on a similar tutorial for managing policies from the CLI and I noticed a few small typos in the UI version.
=> fixing typos in How to create policies in the Chainguard Enforce Console

content/software-security/glossary.md
Fix typo
Fix typo in documentation
N/A
N/A
N/A
=> Fix typo in content/software-security/glossary.md

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/alternative-installation-methods.md
Adds documentation for new declarative install features in Enforce Agent.
Address users who wish to install Enforce Agent without `chainctl`.
=> add documentation for additional Chainguard Enforce Agent install methods

layouts/partials/head/script-header.html
This PR adds CSP rules to protect against XSS attacks.
We had a report from a user that the search box would allow for inline script execution.
Type the following in the search box and you should see a prompt/dialog come up in the current site, while with the changes (check preview site) the inline script execution is blocked by the browser.
```
"><img src=x onerror=prompt(document.domain);>
```
=> Adding global CSP rules

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-policy-examples.md
We're updating the policies from the example article on the UI to keep everything as up-to-date as possible, so I wanted to port those changes over here as well! Once https://github.com/chainguard-dev/console-ui/pull/574 gets merged in, I will mark this as ready for review, in case there are other changes forthcoming.
Trying to keep our example, public-facing policies up-to-date and consistent across our properties!
=> Update policies in example article

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-policies-cli.md, content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-policies-ui/index.md, content/open-source/sigstore/cosign/how-to-sign-a-container-with-cosign.md
This is a redo of my previous cli-policy-mgmt PR. It captures all the changes made so far to that draft as well as your corrections to some of the `lastmod` dates in the Hugo front matter of a couple other files.
This PR resolves #164
=> Adding the Policy Management on CLI guide, attempt number 2

layouts/partials/head/script-header.html
This PR fixes a typo in the CSP rules that allow access to Google Analytics.
=> Fixed CSP rule for analytics

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/alternative-installation-methods.md
This change is just fixing some broken links in the Alternative Enforce Agent Installation Methods guide.
I was clicking around on this doc and noticed that the internal links weren't entered correctly. I also made a few minor tweaks to the copy that I thought made sense.
=> Fixing broken links in alternative installation guide

content/ui/group.md, content/ui/install.md, content/ui/policy.md
Updates the UI documentation to reflect changes to the policy creation flow in the UI. Users are now sent to a catalog when creating a policy.
=> Update: UI instructions

content/chainguard/chainguard-enforce/chainctl-docs/how-to-install-chainctl.md
Updates `chainctl` install instructions to reflect new release process.
=> update chainctl install instructions

content/open-source/sigstore/fulcio/how-to-inspect-and-verify-fulcio-certificates.md
Signed-off-by: James Petersen <jpetersenames@gmail.com>
Fixing a typo
The previous `step` verification command would fail with
```
❯ step certificate verify fulcio.crt --roots ~/.sigstore/root/targets/fulcio_v1.crt.pem
failed to verify certificate: x509: certificate signed by unknown authority
```
This PR updates the instructions to a working command.
Just fixing a bug
Just needs a review, I tested and confirmed the command works
Just confirm the command works as displayed in the instructions
=> Update the step verification to use intermediate fulcio cert

content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/alternative-installation-methods.md
Updates documentation to reflect the proper required helm value: https://github.com/chainguard-dev/helm-charts/blob/main/charts/enforce-agent/values.yaml#L6
=> correct typo in chainguard enforce helm values

content/chainguard/chainguard-enforce/chainctl-docs/how-to-install-chainctl.md, content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-user-onboarding.md, content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/how-to-install-chainctl.md
Updating `chainctl` docs to reflect new changes and to reflect our style
Signed-off-by: ltagliaferri
=> Update chainctl docs
